import ajax from './ajax'
export const reqAddress = geohash => ajax('/api/position/' + geohash)
export const reqCategorys = () => ajax('/api/index_category')
export const reqShops = ({latitude, longitude}) => ajax('/api/shops', {latitude, longitude})
export const reqSearchGoods = (geohash, keyword) => ajax('/api/search_shops', {geohash, keyword})
export const reqCaptchas = () => ajax('/api/captcha')
export const pwdLogin = (name, pwd, captcha) => ajax('/api/login_pwd', {name,pwd,captcha}, 'POST')
export const sendCode = phone => ajax('/api/sendcode', {phone})
export const smsLogin = (phone, code) => ajax('/api/login_sms', {phone, code}, 'POST')
export const reqUser = () => ajax('/api/userinfo')
export const reqLogout = () => ajax('/api/logout')
export const reqShopInfo = () => ajax('/shop_info')
export const reqShopRatings = () => ajax('/shop_ratings')
export const reqShopGoods = () => ajax('/shop_goods')
